# OLD THEME theme: jekyll-theme-minimal
#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

workshop_title: "Introductory Scientific Computing Workshops"
workshop_edition: "Fall 2020"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Overall info for pages.
title: "Columbia Psychology Scientific Computing"
org: "cu-psych-computing"

# What kind of thing is this ("workshop" or "lesson")?
# TODO: Remove dependency on site.kind since we are going rogue
kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Email address, no mailto:
# (Don't change this -- the contact address for your workshop will be set 
# in the index.md file)
email: "psych-methods-support@columbia.edu"

# Sites.
amy_site: "https://amy.software-carpentry.org/workshops"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "https://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"

# Surveys.
pre_survey: "https://forms.gle/XZzLsVsRdYcEmB8j9"
post_survey: "https://forms.gle/XXNCYp21Nxiaut6P8"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/

# Turn on built-in syntax highlighting.
highlighter: rouge

plugins:
  - jekyll-redirect-from
  - jekyll-paginate